### PR TITLE
feat: Support publish pact with branch

### PR DESCRIPTION
**Pull request by B3nnyL**
## Feature description:
https://github.com/pact-foundation/pact-python/issues/268

## Details:
- Support publishing pacts with branch and a build_url. 
- Use auto_detect_version_properties flag to read branch information from CI. ~~Enable it by default~~

## Actual pacts published with branch:
[broker url](https://bethtest.test.pactflow.io/overview/provider/User%20Service/consumer/UserServiceClient)

### CODE REVIEW

**Comment by YOU54F** [comment]
epic @B3nnyL will take a look at this today, if not, this week. 🙌🏾

**Comment by B3nnyL** [comment]
[PR](https://github.com/pact-foundation/pact-python/pull/301) for fixing broken example message consumer test due to publishing duplicated versions

**Comment by YOU54F** [comment]
Just added some documentation to support

https://github.com/pact-foundation/pact-python/commit/c1da32a9fd45591701ca3802fe8f27789db5f077

**Comment by elliottmurray** [comment]
I need to test this a bit locally first. I don't know what that auto detect does! 

Can I merge this and #302 at the same time? Looks like at least the complexity metric might be an issue?

**Comment by B3nnyL** [comment]
Hello @elliottmurray! Sorry I just saw your reply. auto-detect-version-properties helps CI detects branches , you can explanation from [here](https://docs.pact.io/pact_broker/client_cli/readme#publish)

**Review by YOU54F — APPROVED** [review]

**Comment by YOU54F** [comment]
Tested this out, looks good, branch is optional, and picked up from env vars, if `auto_detect_version_properties` set to True

I'd maybe tighten up the `auto_detect_version_properties` to accept `True` and not `Any` as it allows `"true"` but expects `True`.

```
        broker = Broker(broker_base_url="https://saf.pactflow.io", broker_token='foobar')
        broker.publish("Consumer_a",
                       "2.0.3",
                       auto_detect_version_properties=True,  # Uses common CI env vars such as GIT_BRANCH
                       #    branch='consumer-branch',
                       tag_with_git_branch=True,
                       pact_dir='.')
```

Nice work @B3nnyL

**Pull request merged**
