### PR TITLE
Allow newer versions of requests

### PR DESCRIPTION
**Pull request by bassdread**
Fixes https://github.com/pact-foundation/pact-python/issues/47

### CODE REVIEW

**Comment by jslvtr** [comment]
Not too sure about this—if we stick to one known version, it's less likely bugs will be introduced by future versions. I think we should only upgrade to future versions if we find we need to because the current version has a bug or new versions introduce new functionality we want.

**Comment by matthewbalvanz-wf** [comment]
As a library that others are likely to include in other projects, this kind of flexibility is handy, because it offers flexibility for the project to decide which version they want to use.

I did some testing with requests and pact-python and it looks like anything from 2.5.0 to the latest release should work properly. @bassdread  would you be willing to update your PR to open it up with: requests>=2.5.0,<3.0.0? If a major version is released we'll likely want to do some checking on what changed in that release before its used with pact-python.

**Comment by bassdread** [comment]
@matthewbalvanz-wf apologies for the late reply, I have updated this.

I don't mind which option is used to fixed this issue. Feel free to use this or close it if there is a better option.

**Comment by matthewbalvanz-wf** [comment]
Thanks @bassdread. I'm going to merge both and spend a little time sorting out what the minimums are for the project and get a new release cut.

**Pull request merged**
