### PR TITLE
Converting to kwargs

### PR DESCRIPTION
**Pull request by elliottmurray**
Attempt to convert to kwargs in setup for Pycharm

### CODE REVIEW

**Comment by antonagestam** [comment]
@mefellows This hopefully solves #111. There isn't anything programatically wrong with building the dict and then calling the function with its expansion. But, my guess is that this prevents PyCharm from statically parsing the file. So this is more about adhering to the current limits/design problems of Python packaging.

I'll try to get the time to test this out when I have the time!

**Comment by mefellows** [comment]
Ah cool, that makes sense. Carry on :)

**Comment by bethesque** [comment]
I totally know what a KWARGS are and I KWARG all the time, this is great KWARGING, there should be more of it, hooray for KWARGS!

**Comment by bethesque** [comment]
Given I have NFI what this is about, I'll just see if other other Matt wants to weigh in before we merge this.

**Pull request merged**
