### PR TITLE
test(examples): tidy build and flask/fastapi examples, improve consistency

### PR DESCRIPTION
**Pull request by mikegeeves**
re #270

### CODE REVIEW

**Comment by mikegeeves** [comment]
> This is looking really awesome btw. I'm trying to get it to run locally to help get it over the lone but having some issues with install to do with ruby binaries. I think an earlier commit added some options and has some unintended consequences I'm trying to unpick.

Thanks :)
It wasn't running the FastAPI examples before from the Makefile, and the scripts didn't quite work right so it might be from that, still very much WIP/Draft!
The consumer and Flask examples are pretty much there, FastAPI and messager I still need to look at, so half way there.
In the Flask example it's running flask from the run_pytest.sh script, but FastAPI is also running it as a fixture, need to figure out where to go with that one, I think probably the fixture.
Anyway, making progress

**Comment by mikegeeves** [comment]
> So I originally set it up so there were a few different examples. The fixture one I added to show how to run with pytest. Also there is an issue that was beyond my python of getting Flask to run as a sub process to do with tickle (they made some changes that effectively broke it and the script was the only way I could get it to work)

I think that's ok, it's helpful to show different approaches, but can be confusing without the "why" being clear.
I'm going for more of a central examples README, rather than the individual ones per folder, to be able to compare/contrast them there, what do you think? Started but in progress

**Comment by elliottmurray** [comment]
Just checking @mikegeeves I can close this as we've merged it?

**Comment by mikegeeves** [comment]
Think it's fine for now to close yes, there will be more later but that can go separately

**Pull request closed without merging**
