### PR TITLE
Consumer Compatibility Suite (V1)

### PR DESCRIPTION
**Pull request by JP-Ellis**
## :memo: Summary

This implements the first (of many) compatibility suite tests: `V1/http_consumer.feature`.

This PR focuses primarily on the compatibility suite, but also includes a few changes to the `v3` module in order to implement features required for the compatibility suite, or bugs identified as a result of the compatibility suite.

A couple of scenarios from the feature file have been disabled for now, pending on a resolution from upstream.

### Note to the reviewer

As this PR includes a few changes to other parts of the codebase, it might be best to review the PR on a per-commit basis.

## :rotating_light: Breaking Changes

None related to the existing `v2` module

## :hammer: Test Plan

Compatibility suite is the test plan.

## :link: Related issues/PRs

- Part of #420 
- Resolves: #473

### CODE REVIEW

**Comment by rholshausen** [comment]
LGTM

**Review by mefellows — APPROVED** [review]
Nice work! I mostly just browsed through it rather than fine tooth comb given the volume. The regex and other syntax for the parameterization is obscure/interesting, but it looks to have done the job!

**Comment by JP-Ellis** [comment]
It should is pretty standard Python regex, with the main uncommon feature being the naming of groups using `(?P<name>...)`. This is required to ensure the group can be referenced by name 🙂

**Comment by mefellows** [comment]
Oh, I just meant it's kind of funky to read it in the descriptions that way. The `negation` thing was also cool.

**Comment by YOU54F** [comment]
Might be worth adding in the docs that to run these, one would have to pull in the submodules

`git submodule update --init`

**Review by YOU54F — APPROVED** [review]

**Comment by YOU54F** [comment]
cirrus-ci looks like they are failing due to not checking out submodules 👍🏾

**Pull request merged**
