### PR TITLE
initial pact-message support

### PR DESCRIPTION
**Pull request by dwang7**

### CODE REVIEW

**Comment by dwang7** [comment]
sample test

def test_message(pact):

    return

    message = pact.add_message()

    data = {
        "id": "12334",
        "name": "david"
    }

    (message.given("test message state")
            .expects_to_receive("test message ")
            .with_metadata("Content-type': 'application/json")
            .with_contents(data))

    message2 = pact.add_message()

    data2 = {
        "id": "45676",
        "name": "steven"
    }

    (message2.given("test message2 state")
             .expects_to_receive("test2 message ")
             .with_metadata("Content-type': 'application/json")
             .with_contents(data2))

    pact.verify_message(rmq_handler)

**Comment by zeldigas** [comment]
@dwang7 is your adds support only for consumer part or for provider as well? I'd be happy to use your WIP version until it's get merged to mainline for testing message producer written in python

**Comment by alecgerona** [comment]
Any update for this @dwang7?

**Comment by cathleenyuan** [comment]
could any one fix the conflict file there @, it would be great to have this feature ready . Thanks the team's effort  !! @dwang7 @dwang7

**Comment by mefellows** [comment]
Should we close this in favour of #193 ?

**Comment by elliottmurray** [comment]
Has been superceded

**Pull request closed without merging**
