### PR TITLE
docs(examples-consumer): add pip install requirements to the consumer…

### PR DESCRIPTION
**Pull request by mikegeeves**
… example

### CODE REVIEW

**Comment by YOU54F** [comment]
The tests failed 🤔  I've not looked at the pact-python builds, are they flakey? Do they need the hamster wheel turning again?

**Comment by YOU54F** [comment]
> Connection refused - connect(2) for "localhost" port 5001 

provider failed to start, it looks like.

**Comment by elliottmurray** [comment]
I haven't seen this - looking at setup.py and it doesn't have fixed versions of fastapi and uvicorn and wondering if that is causing the issue - e.g:
```python
    'fastapi>=0.67.0',
    'urllib3>=1.26.5',
    'uvicorn>=0.14.0'
```

If a retrigger doesn't work I'll try and find some time this week to have a look. Some PR's to chase up on I see....

**Comment by mikegeeves** [comment]
It was happening back in December, I think I fixed it as part of this one: https://github.com/pact-foundation/pact-python/pull/280 (at least the build was broken then worked!) But I can't see a fixing change currently (using my phone)

**Comment by mikegeeves** [comment]
> ImportError: cannot import name 'json' from 'itsdangerous'
Looks like this: https://serverfault.com/questions/1094062/error-from-itsdangerous-import-json-as-json-importerror-cannot-import-name-j

Updating Flask to 1.1.4

https://itsdangerous.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

I have no clue what itsdangerous is :open_mouth: 

https://github.com/aws/aws-sam-cli/issues/3661

...and fixing markupsafe to 2.0.1

**Review by elliottmurray — APPROVED** [review]

**Pull request merged**
